// Code generated by protoc-gen-go. DO NOT EDIT.
// source: graph.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Graph struct {
	Edge                 []*Edge  `protobuf:"bytes,1,rep,name=edge,proto3" json:"edge,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Graph) Reset()         { *m = Graph{} }
func (m *Graph) String() string { return proto.CompactTextString(m) }
func (*Graph) ProtoMessage()    {}
func (*Graph) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e4c656902fc0e6b, []int{0}
}

func (m *Graph) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Graph.Unmarshal(m, b)
}
func (m *Graph) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Graph.Marshal(b, m, deterministic)
}
func (m *Graph) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Graph.Merge(m, src)
}
func (m *Graph) XXX_Size() int {
	return xxx_messageInfo_Graph.Size(m)
}
func (m *Graph) XXX_DiscardUnknown() {
	xxx_messageInfo_Graph.DiscardUnknown(m)
}

var xxx_messageInfo_Graph proto.InternalMessageInfo

func (m *Graph) GetEdge() []*Edge {
	if m != nil {
		return m.Edge
	}
	return nil
}

// Our address book file is just one of these.
type Edge struct {
	EdgeId               int64    `protobuf:"varint,1,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	From                 int64    `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   int64    `protobuf:"varint,3,opt,name=to,proto3" json:"to,omitempty"`
	Cost                 float64  `protobuf:"fixed64,4,opt,name=cost,proto3" json:"cost,omitempty"`
	PointId              []int64  `protobuf:"varint,5,rep,packed,name=point_id,json=pointId,proto3" json:"point_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Edge) Reset()         { *m = Edge{} }
func (m *Edge) String() string { return proto.CompactTextString(m) }
func (*Edge) ProtoMessage()    {}
func (*Edge) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e4c656902fc0e6b, []int{1}
}

func (m *Edge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Edge.Unmarshal(m, b)
}
func (m *Edge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Edge.Marshal(b, m, deterministic)
}
func (m *Edge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Edge.Merge(m, src)
}
func (m *Edge) XXX_Size() int {
	return xxx_messageInfo_Edge.Size(m)
}
func (m *Edge) XXX_DiscardUnknown() {
	xxx_messageInfo_Edge.DiscardUnknown(m)
}

var xxx_messageInfo_Edge proto.InternalMessageInfo

func (m *Edge) GetEdgeId() int64 {
	if m != nil {
		return m.EdgeId
	}
	return 0
}

func (m *Edge) GetFrom() int64 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *Edge) GetTo() int64 {
	if m != nil {
		return m.To
	}
	return 0
}

func (m *Edge) GetCost() float64 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func (m *Edge) GetPointId() []int64 {
	if m != nil {
		return m.PointId
	}
	return nil
}

func init() {
	proto.RegisterType((*Graph)(nil), "pb.Graph")
	proto.RegisterType((*Edge)(nil), "pb.Edge")
}

func init() { proto.RegisterFile("graph.proto", fileDescriptor_3e4c656902fc0e6b) }

var fileDescriptor_3e4c656902fc0e6b = []byte{
	// 163 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x1c, 0x8e, 0x3d, 0x0a, 0x02, 0x31,
	0x10, 0x46, 0xc9, 0xcf, 0xfe, 0x30, 0x0b, 0x16, 0xd3, 0x18, 0xc1, 0x22, 0x2c, 0x08, 0xa9, 0xb6,
	0xd0, 0x33, 0x88, 0x6c, 0x9b, 0x0b, 0x88, 0x6b, 0xd6, 0xb8, 0x85, 0x4e, 0x88, 0xb9, 0x3f, 0x92,
	0xe9, 0xde, 0x7b, 0x0c, 0xc3, 0x07, 0x43, 0xcc, 0x8f, 0xf4, 0x9e, 0x52, 0xa6, 0x42, 0x28, 0xd3,
	0x32, 0x9e, 0xa0, 0xb9, 0xd5, 0x84, 0x47, 0xd0, 0x6b, 0x88, 0xab, 0x11, 0x56, 0xb9, 0xe1, 0xdc,
	0x4f, 0x69, 0x99, 0xae, 0x21, 0xae, 0x9e, 0xeb, 0x98, 0x41, 0x57, 0xc3, 0x3d, 0x74, 0xd5, 0xef,
	0x5b, 0x30, 0xc2, 0x0a, 0xa7, 0x7c, 0x5b, 0x75, 0x0e, 0x88, 0xa0, 0x5f, 0x99, 0x3e, 0x46, 0x72,
	0x65, 0xc6, 0x1d, 0xc8, 0x42, 0x46, 0x71, 0x91, 0x85, 0xea, 0xcd, 0x93, 0x7e, 0xc5, 0x68, 0x2b,
	0x9c, 0xf0, 0xcc, 0x78, 0x80, 0x3e, 0xd1, 0xf6, 0x2d, 0xf5, 0x63, 0x63, 0x95, 0x53, 0xbe, 0x63,
	0x9f, 0xc3, 0xd2, 0xf2, 0xca, 0xcb, 0x3f, 0x00, 0x00, 0xff, 0xff, 0x17, 0x12, 0xcf, 0x65, 0xb4,
	0x00, 0x00, 0x00,
}
